pipeline{
    agent {label "tf-agent"}
    environment{
        AWS_ACCESS_KEY_ID = credentials('aws_access_key_id')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
        AWS_DEFAULT_REGION = 'us-east-1'
        BUILD_RESULT= "${currentBuild.result}"
        CURRENT_RESULT= "${currentBuild.currentResult}"
    }
    stages{
        stage('Checkout scm'){
            steps{
                checkout scm
            }
        }
        stage('Terraform initialization'){
            steps{
                dir('env/'){
                    sh '''
                    echo "---Initialization---"
                    terraform init
                    '''
                }
            }
        }
        stage('Plan'){
            steps{
                dir('env/'){
                    sh '''
                    echo "--terraform plan---"
                    terraform plan -out=tfplan
                    echo "--plan stored in tfplan"
                    '''
                }
            }
        }
        stage('Apply'){
            steps{
                dir('env/'){
                    sh '''
                    echo "--applying tfplan---"
                    terraform apply -input=false tfplan
                    '''
                }
            }
        }
        stage('Status'){
            steps{
                dir('env/'){
                    sh '''
                    echo "--status---"
                    terraform show

                    echo "terraform outputs"
                    terraform output
                    '''
                }
            }
        }
    }
    post{
        always{
            sh '''
            echo "build finished with status: $BUILD_RESULT || $CURRENT_RESULT"
            '''
        }
        failure{
            mail to: 'sshalyal42@gmail.com', subject: 'Build failed.'
        }
    }
}